tasks:
  - name: Dependencies 
    init: |
      sudo add-apt-repository ppa:redislabs/redis
      sudo apt-get update
      sudo apt-get -y install redis
      
  - name: Virtual Environment setup
    init: |
      sudo apt-get -y install python3.8
      python -m venv venv38 --system-site-packages
      source venv38/bin/activate
      pip install -r "requirements.txt"
    
  - name: run redis
    command: redis-server
  - name: run FastAPI
    command: uvicorn main:app
