tasks:
  - name: Dependencies 
    command: |
      sudo add-apt-repository ppa:redislabs/redis
      sudo apt-get update
      sudo apt-get install redis
      sudo apt-get install python3.8
  - name: Virtual Environment setup
    command: python -m venv venv38
  - name: Enter Virtual Environment 
    command: source venv38/bin/activate # need to still add running redis-server
  - name: download pip dependencies
    command: pip install -r "requirements.txt"
    
